# Page settings
BaseURL = "https://zjuvis.github.io/"
Title = "ZJUVIS"
LanguageCode = "en-us"
theme = "zjuvis"
publishDir = "docs"

[Params]
  GroupName = "ZJUVIS"

  # Meta
  Author = "ZJUVIS"
  Description = "ZJUVIS Research Group Home"
  Email = "zjuvis@gmail.com"
  Keywords = "ZJUVIS, visualization, visual analysis, academic, research, Zhejiang University"

  [Params.Carousel]
    Height = 420
    [[Params.Carousel.Items]]
      Title = "Our paper has been accepted by ACM CHI 2018!"
      Description = "HomeFinder Revisited: Finding Ideal Homes with Reachability-Centric Multi-Criteria Decision Making"
      Image = "/images/projects/reach.png"
    [[Params.Carousel.Items]]
      Title = "Ji Lan presenting iTTVis on IEEE VIS 2017"
      Description = "iTTVis: Interactive Visualization of Table Tennis Data"
      Image = "/images/vis2017.jpg"
    [[Params.Carousel.Items]]
      Title = "Our paper has been accepted by IEEE InfoVis 2017!"
      Description = "iTTVis: Interactive Visualization of Table Tennis Data"
      Image = "/images/projects/ittvis.jpg"

  [Params.Demo]
    [[Params.Demo.Items]]
      Title = "ReACH"
      Description = "Finding an ideal home is a difficult and laborious process. By characterizing user requirements and analytical tasks in the context of finding ideal homes, we designed ReACH, a novel visual analytics system that assists people in finding, evaluating, and choosing a home based on multiple criteria, including reachability."
      Image = "/images/projects/reach.png"
      Source = "ACM CHI 2018"
      Paper = "/files/reach.pdf"
      Video = "https://youtu.be/WcjMXAfuygg"

    [[Params.Demo.Items]]
      Title = "iTTVis"
      Description = "We propose iTTVis, a novel interactive table tennis visualization system, which to our knowledge, is the first visual analysis system for analyzing and exploring table tennis data. iTTVis provides a holistic visualization of an entire match from three main perspectives, namely, time-oriented, statistical, and tactical analyses."
      Image = "/images/projects/ittvis.jpg"
      Source = "InfoVis 2017"
      Paper = "/files/ittvis.pdf"
      Video = "/videos/ittvis.mp4"
      Demo = "/iTTVis"
      Page = '/ittvis_framework'

  [Params.Publications]
    [[Params.Publications.Items]]
      Year = "2018"
      Title = "A Semantic-based Method for Visualizing Large Image Collections"
      Journal = "IEEE Transactions on Visualization and Computer Graphics"
      Paper = "/files/imgvis.pdf"
      Video = "/videos/imgvis.mp4"
      Authors = ["Xiao Xie*", "Xiwen Cai*", "Junpei Zhou*", "Nan Cao", "Yingcai Wu*"]

    [[Params.Publications.Items]]
      Year = "2018"
      Title = "A Study of the Effect of Doughnut Chart Parameters on Proportion Estimation Accuracy"
      Journal = "Computer Graphics Forum"
      Paper = "/files/donutchart.pdf"
      DOI = "10.1111/cgf.13325"
      Authors = ["Xiwen Cai*", "Konstantinos Efstathiou", "Xiao Xie*", "Yingcai Wu*", "Yan Shi", "Lingyun Yu"]

    [[Params.Publications.Items]]
      Year = "2018"
      Title = "HomeFinder Revisited: Finding Ideal Homes with Reachability-Centric Multi-Criteria Decision Making"
      Journal = "Proc. of the ACM CHI 2018"
      Paper = "/files/reach.pdf"
      DOI = "10.1145/3173574.3173821"
      Video = "https://youtu.be/WcjMXAfuygg"
      Authors = ["Di Weng*", "Heming Zhu*", "Jie Bao", "Yu Zheng", "Yingcai Wu*"]

    [[Params.Publications.Items]]
      Year = "2017"
      Title = "Exploring the design space of immersive urban analytics"
      Journal = "Visual Informatics"
      DOI = "10.1016/j.visinf.2017.11.002"
      Paper = "/files/arvis.pdf"
      Authors = ["Zhutian Chen*", "Yifang Wang*", "Tianchen Sun*", "Xiang Gao", "Wei Chen", "Zhigeng Pan", "Huamin Qu", "Yingcai Wu*"]

    [[Params.Publications.Items]]
      Year = "2017"
      Title = "Querying Massive Trajectories by Path on the Cloud"
      Journal = "Proc. of the ACM SIGSPATIAL 2017 [Short Paper]"
      Paper = "/files/PathQuery_Zheng_SIGSPATIAL17.pdf"
      Authors = ["Ruiyuan Li", "Sijie Ruan", "Jie Bao", "Yanhua Li", "Yingcai Wu*", "Yu Zheng"]

    [[Params.Publications.Items]]
      Year = "2017"
      Title = "Examining the effects of network externalities, density, and closure on in-game currency price in online games"
      Journal = "Internet Research"
      DOI = "10.1108/IntR-07-2016-0201"
      Authors = ["Xuexin Xu", "Xiaodong Yang", "Junhua Lu", "Ji Lan*", "Tai-Quan Peng", "Yingcai Wu*", "Wei Chen"]

    [[Params.Publications.Items]]
      Year = "2017"
      Title = "StreamExplorer: A Multi-Stage System for Visually Exploring Events in Social Streams"
      Journal = "IEEE Transactions on Visualization and Computer Graphics"
      DOI = "10.1109/TVCG.2017.2764459"
      Paper = "/files/streamexplorer.pdf"
      Authors = ["Yingcai Wu*", "Zhutian Chen*", "Guodao Sun", "Xiao Xie*", "Nan Cao", "Shixia Liu", "Weiwei Cui"]
      Video = "/videos/streamexplorer.mp4"

    [[Params.Publications.Items]]
      Year = "2017"
      Title = "Cluster-based Visual Abstraction for Multivariate Scatterplots"
      Journal = "IEEE Transactions on Visualization and Computer Graphics"
      DOI = "10.1109/TVCG.2017.2754480"
      Paper = "/files/scatterplots.pdf"
      Authors = ["Hongsen Liao*", "Yingcai Wu*", "Li Chen", "Wei Chen"]

    [[Params.Publications.Items]]
      Year = "2017"
      Title = "iTTVis: Interactive Visualization of Table Tennis Data"
      Journal = "IEEE Transactions on Visualization and Computer Graphics (IEEE InfoVis 2017)"
      DOI = "10.1109/TVCG.2017.2744218"
      Paper = "/files/ittvis.pdf"
      Video = "/videos/ittvis.mp4"
      Demo = "/iTTVis"
      Authors = ["Yingcai Wu*", "Ji Lan*", "Xinhuan Shu*", "Chenyang Ji*", "Kejian Zhao*", "Jiachen Wang*", "Hui Zhang"]

    [[Params.Publications.Items]]
      Year = "2016"
      Title = "Similarity Voting based Viewpoint Selection for Volumes"
      Journal = "Computer Graphics Forum (EuroVis 2016)"
      DOI = "10.1111/cgf.12915"
      Authors = ["Yubo Tao", "Qirui Wang", "Wei Chen", "Yingcai Wu*", "Hai Lin"]

    [[Params.Publications.Items]]
      Year = "2016"
      Title = "A Survey on Visual Analytics of Social Media Data"
      Journal = "IEEE Transactions on Multimedia"
      DOI = "10.1109/TMM.2016.2614220"
      Paper = "/files/tmm-survey.pdf"
      Authors = ["Yingcai Wu*", "Nan Cao", "David Gotz", "Yap-Peng Tan", "Daniel A. Keim"]

    [[Params.Publications.Items]]
      Year = "2016"
      Title = "Mining the Most Influential k-Location Set from Massive Trajectories"
      Journal = "Proc. of the ACM SIGSPATIAL 2016"
      DOI = "10.1145/2996913.2997009"
      Paper = "/files/trajectorycoverage_zheng.pdf"
      Authors = ["Yuhong Li", "Jie Bao", "Yanhua Li", "Yingcai Wu*", "Zhiguo Gong", "Yu Zheng"]

    [[Params.Publications.Items]]
      Year = "2016"
      Title = "SmartAdP: Visual Analytics of Large-scale Taxi Trajectories for Selecting Billboard Locations"
      Journal = "IEEE Transactions on Visualization and Computer Graphics (IEEE VAST 2016)"
      DOI = "10.1109/TVCG.2016.2598432"
      Paper = "/files/smartadp.pdf"
      Video = "/videos/smartadp.mp4"
      Demo = "http://smartadp.chinacloudapp.cn/"
      Authors = ["Dongyu Liu*", "Di Weng*", "Yuhong Li", "Jie Bao", "Yu Zheng", "Huamin Qu", "Yingcai Wu*"]

    [[Params.Publications.Items]]
      Year = "2016"
      Title = "Embedding Spatio-temporal Information into Maps by Route-Zooming"
      Journal = "IEEE Transactions on Visualization and Computer Graphics"
      DOI = "10.1109/TVCG.2016.2535234"
      Paper = "/files/road_broadening.pdf"
      Authors = ["Guodao Sun*", "Ronghua Liang", "Huamin Qu", "Yingcai Wu*"]

    [[Params.Publications.Items]]
      Year = "2016"
      Title = "PieceStack: Toward Better Understanding of Stacked Graphs"
      Journal = "IEEE Transactions on Visualization and Computer Graphics (IEEE PacificVis 2016)"
      DOI = "10.1109/TVCG.2016.2534518"
      Paper = "/files/piecestack.pdf"
      Authors = ["Tongshuang Wu", "Yingcai Wu*", "Conglei Shi", "Huamin Qu", "Weiwei Cui"]

    [[Params.Publications.Items]]
      Year = "2016"
      Title = "PeakVizor: Visual Analytics of Peaks in Video Clickstreams from Massive Open Online Courses"
      Journal = "IEEE Transactions on Visualization and Computer Graphics"
      DOI = "10.1109/TVCG.2015.2505305"
      Paper = "/files/peakvizor.pdf"
      Authors = ["Qing Chen", "Yuanzhe Chen", "Dongyu Liu", "Conglei Shi", "Yingcai Wu*", "Huamin Qu"]

    [[Params.Publications.Items]]
      Year = "2016"
      Title = "Follower-followee Network, Communication Networks and Vote Agreement of U.S. Members of Congress"
      Journal = "Communication Research"
      DOI = "10.1177/0093650214559601"
      Paper = "http://journals.sagepub.com/doi/pdf/10.1177/0093650214559601"
      Authors = ["Tai-Quan Peng", "Mengchen Liu", "Yingcai Wu*", "Shixia Liu"]

  [Params.News]
    [[Params.News.Items]]
      Date = "Sep 1, 2017 - Pinned"
      Summary = "We are looking for strongly-motivated PostDoc, PhD, Master, and undergraduate students to join us! If you are interested in visualization research, please <a href=\"/contact/\">contact us</a>."
    [[Params.News.Items]]
      Date = "Feb 5th, 2018"
      Summary = "Our paper <b>A Semantic-based Method for Visualizing Large Image Collections</b> has been accepted by IEEE TVCG."
    [[Params.News.Items]]
      Date = "Dec 12, 2017"
      Summary = "Our paper <b>HomeFinder Revisited: Finding Ideal Homes with Reachability-centric Multi-Criteria Decision Making</b> has been conditionally accepted by ACM CHI 2018."
    [[Params.News.Items]]
      Date = "Nov 24, 2017"
      Summary = "Ji Lan, one of our Ph.D. students, has received National Scholarship. Congratulations!"
    [[Params.News.Items]]
      Date = "Nov 24, 2017"
      Summary = "Junpei Zhou, one of our undergraduate students, has been awarded Chu Kochen Scholarship. This is the second Chu Kochen Scholarship awarded to our undergraduate group members in two consecutive years, congratulations!"
    [[Params.News.Items]]
      Date = "Oct 17, 2017"
      Summary = "Our new site has been deployed! Check at <a href=\"http://zjuvis.org/\">http://zjuvis.org/</a>."

  [Params.Members]
    [[Params.Members.Items]]
      Name = "Xiao Xie"
      Photo = "images/people/xiexiao.jpg"
      Position = "Ph.D. Since 2015"
      URL = "http://ssxiexiao.github.io/about/"
    [[Params.Members.Items]]
      Name = "Xiwen Cai"
      Photo = "images/people/caixiwen.jpg"
      Position = "Master Since 2015"
      URL = "https://github.com/seevencai"
    [[Params.Members.Items]]
      Name = "Di Weng"
      Photo = "images/people/wengdi.jpg"
      Position = "Ph.D. Since 2016"
      URL = "https://polymorphism.ac.cn"
    [[Params.Members.Items]]
      Name = "Ji Lan"
      Photo = "images/people/lanji.png"
      Position = "Ph.D. Since 2016"
      URL = "https://lanjizju.github.io/"
    [[Params.Members.Items]]
      Name = "Tan Tang"
      Photo = "images/people/tangtan.jpg"
      Position = "Ph.D. Since 2016"
      URL = "http://www.tantang.org/"
    [[Params.Members.Items]]
      Name = "Sadia Rubab"
      Photo = "images/people/sadiarubab.png"
      Position = "Ph.D. Since 2017"
      URL = "https://www.researchgate.net/profile/Sadia_Rubab"
    [[Params.Members.Items]]
      Name = "Heming Zhu"
      Photo = "images/people/zhuheming.jpg"
      Position = "Master Since 2017"
      URL = "http://wootwootwo.me/"
    [[Params.Members.Items]]
      Name = "Kaijuan Yuan"
      Photo = "images/people/yuankaijuan.jpg"
      Position = "Master Since 2017"
      URL = "https://www.linkedin.com/in/kaijuan-yuan-362326b9/"
    [[Params.Members.Items]]
      Name = "Kejian Zhao"
      Photo = "images/people/zhaokejian.jpg"
      Position = "Master Since 2017"
      URL = "https://zhaokejian.github.io/about/"
    [[Params.Members.Items]]
      Name = "Dazhen Deng"
      Photo = "images/people/dengdazhen.jpg"
      Position = "Undergraduate"
      URL = "#"
    [[Params.Members.Items]]
      Name = "Hongye Liang"
      Photo = "images/people/lianghongye.jpg"
      Position = "Undergraduate"
      URL = "#"
    [[Params.Members.Items]]
      Name = "Jiachen Wang"
      Photo = "images/people/wangjiachen.jpg"
      Position = "Undergraduate"
      URL = "#"
    [[Params.Members.Items]]
      Name = "Ran Chen"
      Photo = "images/people/chenran.png"
      Position = "Undergraduate"
      URL = "#"
    [[Params.Members.Items]]
      Name = "Yifang Wang"
      Photo = "images/people/wangyifang.jpg"
      Position = "Undergraduate"
      URL = "http://wangyifang.top/about/"
    [[Params.Members.Items]]
      Name = "Zikun Deng"
      Photo = "images/people/dengzikun.jpg"
      Position = "Undergraduate"
      URL = "https://mrsoldiers.github.io/"

  [Params.IttvisTools]
    [[Params.IttvisTools.Items]]
      Name = "iTTVis Instruction"
      URL = "/ittvis_framework/ittvis"
    [[Params.IttvisTools.Items]]
      Name = "iSSVis Instruction"
      URL = "/ittvis_framework/issvis"

  [Params.IttvisFrameworkCoreTeam]
    [[Params.IttvisFrameworkCoreTeam.Items]]
      Name = "Yingcai Wu"
      Photo = "images/ittvis_framework/ycwu.jpg"
      Description = "Assistant Professor, Zhejiang University"
      URL = "http://www.ycwu.org"
    [[Params.IttvisFrameworkCoreTeam.Items]]
      Name = "Ji Lan"
      Photo = "images/people/lanji.png"
      Description = "PhD Student, Zhejiang University"
      URL = "https://lanjizju.github.io/"
    [[Params.IttvisFrameworkCoreTeam.Items]]
      Name = "Jiachen Wang"
      Photo = "images/people/wangjiachen.jpg"
      Description = "PhD Student, Zhejiang University"
      URL = "#"
    [[Params.IttvisFrameworkCoreTeam.Items]]
      Name = "Kejian Zhao"
      Photo = "images/people/zhaokejian.jpg"
      Description = "Master Student, Zhejiang University"
      URL = "https://zhaokejian.github.io/about/"
    [[Params.IttvisFrameworkCoreTeam.Items]]
      Name = "Xinhuan Shu"
      Photo = "images/ittvis_framework/shuxinhuan.jpg"
      Description = "PhD Student, HKUST"
      URL = "https://shuxinhuan.github.io/about/"
    [[Params.IttvisFrameworkCoreTeam.Items]]
      Name = "Chenyang Ji"
      Photo = "images/ittvis_framework/jichenyang.png"
      Description = "Master Student, Yale University"
      URL = "https://chenyangji.wordpress.com/"
    [[Params.IttvisFrameworkCoreTeam.Items]]
      Name = "Jiang Wu"
      Photo = "images/ittvis_framework/wujiang.jpeg"
      Description = "Undergraduate Student, Zhejiang University"
      URL = "#"

  [Params.IttvisCoreTeam]
    [[Params.IttvisCoreTeam.Items]]
      Name = "Yingcai Wu"
      Photo = "images/ittvis_framework/ycwu.jpg"
      Description = "Assistant Professor, Zhejiang University"
      URL = "http://www.ycwu.org"
    [[Params.IttvisCoreTeam.Items]]
      Name = "Ji Lan"
      Photo = "images/people/lanji.png"
      Description = "PhD Student, Zhejiang University"
      URL = "https://lanjizju.github.io/"
    [[Params.IttvisCoreTeam.Items]]
      Name = "Jiachen Wang"
      Photo = "images/people/wangjiachen.jpg"
      Description = "PhD Student, Zhejiang University"
      URL = "#"
    [[Params.IttvisCoreTeam.Items]]
      Name = "Kejian Zhao"
      Photo = "images/people/zhaokejian.jpg"
      Description = "Master Student, Zhejiang University"
      URL = "https://zhaokejian.github.io/about/"
    [[Params.IttvisCoreTeam.Items]]
      Name = "Xinhuan Shu"
      Photo = "images/ittvis_framework/shuxinhuan.jpg"
      Description = "PhD Student, HKUST"
      URL = "https://shuxinhuan.github.io/about/"
    [[Params.IttvisCoreTeam.Items]]
      Name = "Chenyang Ji"
      Photo = "images/ittvis_framework/jichenyang.png"
      Description = "Master Student, Yale University"
      URL = "https://chenyangji.wordpress.com/"

  [Params.IssvisCoreTeam]
    [[Params.IssvisCoreTeam.Items]]
      Name = "Yingcai Wu"
      Photo = "images/ittvis_framework/ycwu.jpg"
      Description = "Assistant Professor, Zhejiang University"
      URL = "http://www.ycwu.org"
    [[Params.IssvisCoreTeam.Items]]
      Name = "Ji Lan"
      Photo = "images/people/lanji.png"
      Description = "PhD Student, Zhejiang University"
      URL = "https://lanjizju.github.io/"
    [[Params.IssvisCoreTeam.Items]]
      Name = "Jiachen Wang"
      Photo = "images/people/wangjiachen.jpg"
      Description = "PhD Student, Zhejiang University"
      URL = "#"
    [[Params.IssvisCoreTeam.Items]]
      Name = "Kejian Zhao"
      Photo = "images/people/zhaokejian.jpg"
      Description = "Master Student, Zhejiang University"
      URL = "https://zhaokejian.github.io/about/"
    [[Params.IssvisCoreTeam.Items]]
      Name = "Jiang Wu"
      Photo = "images/ittvis_framework/wujiang.jpeg"
      Description = "Undergraduate, Zhejiang University"
      URL = "#"
    [[Params.IssvisCoreTeam.Items]]
      Name = "Xinhuan Shu"
      Photo = "images/ittvis_framework/shuxinhuan.jpg"
      Description = "PhD Student, HKUST"
      URL = "https://shuxinhuan.github.io/about/"

  [Params.IttvisCollaborator]
    [[Params.IttvisCollaborator.Items]]
      Name = "Hui Zhang"
      Photo = "images/ittvis_framework/zhanghui.jpg"
      Description = "Professor, Zhejiang University"
      URL = "http://mypage.zju.edu.cn/sports_science_zhanghui"
    [[Params.IttvisCollaborator.Items]]
      Name = "Zheng Zhou"
      Photo = "images/ittvis_framework/zhouzheng.jpg"
      Description = "PhD Student, Zhejiang University"
      URL = "#"
