# Page settings
BaseURL = "https://zjuvis.github.io/"
Title = "ZJUVIS"
LanguageCode = "en-us"
theme = "zjuvis"
publishDir = "docs"

[Params]
  GroupName = "ZJUVIS"

  # Meta
  Author = "ZJUVIS"
  Description = "ZJUVIS Research Group Home"
  Email = "zjuvis@gmail.com"
  Keywords = "ZJUVIS, visualization, visual analysis, academic, research, Zhejiang University"

  [Params.Carousel]
    Height = 420
    [[Params.Carousel.Items]]
      Title = "Ji Lan presenting iTTVis on IEEE VIS 2017"
      Description = "iTTVis: Interactive Visualization of Table Tennis Data"
      Image = "/images/vis2017.jpg"
    [[Params.Carousel.Items]]
      Title = "Our paper has been accepted by IEEE InfoVis 2017!"
      Description = "iTTVis: Interactive Visualization of Table Tennis Data"
      Image = "/images/projects/ittvis.jpg"
    [[Params.Carousel.Items]]
      Title = "Our paper has been accepted by IEEE VAST 2016!"
      Description = "SmartAdP: Visual Analytics of Large-scale Taxi Trajectories for Selecting Billboard Locations"
      Image = "/images/projects/smartadp.png"

  [Params.Demo]
    [[Params.Demo.Items]]
      Title = "iTTVis"
      Description = "We propose iTTVis, a novel interactive table tennis visualization system, which to our knowledge, is the first visual analysis system for analyzing and exploring table tennis data. iTTVis provides a holistic visualization of an entire match from three main perspectives, namely, time-oriented, statistical, and tactical analyses."
      Image = "/images/projects/ittvis.jpg"
      Source = "InfoVis 2017"
      Paper = "/files/ittvis.pdf"
      Video = "/videos/ittvis.mp4"
    [[Params.Demo.Items]]
      Title = "SmartAdP"
      Description = "We present SmartAdP, an interactive visual analytics system that deals with the two major challenges including finding good solutions in a huge solution space and comparing the solutions in a visual and intuitive manner. An interactive framework that integrates a novel visualization-driven data mining model enables advertising planners to effectively and efficiently formulate good candidate solutions."
      Image = "/images/projects/smartadp.png"
      Source = "VAST 2016 TVCG"
      Paper = "/files/smartadp.pdf"
      Video = "/videos/smartadp.mp4"
      Demo = "http://smartadp.chinacloudapp.cn/"

  [Params.Publications]
    [[Params.Publications.Items]]
      Year = "2017"
      Title = "StreamExplorer: A Multi-Stage System for Visually Exploring Events in Social Streams"
      Journal = "IEEE Transactions on Visualization and Computer Graphics"
      DOI = "10.1109/TVCG.2017.2764459"
      Paper = "/files/streamexplorer.pdf"
      Authors = ["Yingcai Wu", "Zhutian Chen", "Guodao Sun", "Xiao Xie", "Nan Cao", "Shixia Liu", "Weiwei Cui"]

    [[Params.Publications.Items]]
      Year = "2017"
      Title = "Cluster-based Visual Abstraction for Multivariate Scatterplots"
      Journal = "IEEE Transactions on Visualization and Computer Graphics"
      DOI = "10.1109/TVCG.2017.2754480"
      Paper = "/files/scatterplots.pdf"
      Authors = ["Hongsen Liao", "Yingcai Wu", "Li Chen", "Wei Chen"]

    [[Params.Publications.Items]]
      Year = "2017"
      Title = "iTTVis: Interactive Visualization of Table Tennis Data"
      Journal = "IEEE Transactions on Visualization and Computer Graphics (IEEE InfoVis 2017)"
      DOI = "10.1109/TVCG.2017.2744218"
      Paper = "/files/ittvis.pdf"
      Video = "/videos/ittvis.mp4"
      Authors = ["Yingcai Wu", "Ji Lan", "Xinhuan Shu", "Chenyang Ji", "Kejian Zhao", "Jiachen Wang", "Hui Zhang"]

    [[Params.Publications.Items]]
      Year = "2016"
      Title = "A Survey on Visual Analytics of Social Media Data "
      Journal = "IEEE Transactions on Multimedia"
      DOI = "10.1109/TMM.2016.2614220"
      Paper = "/files/tmm-survey.pdf"
      Authors = ["Yingcai Wu", "Nan Cao", "David Gotz", "Yap-Peng Tan", "and Daniel A. Keim"]

    [[Params.Publications.Items]]
      Year = "2016"
      Title = "SmartAdP: Visual Analytics of Large-scale Taxi Trajectories for Selecting Billboard Locations"
      Journal = "IEEE Transactions on Visualization and Computer Graphics (IEEE VAST 2016)"
      DOI = "10.1109/TVCG.2016.2598432"
      Paper = "/files/smartadp.pdf"
      Video = "/videos/smartadp.mp4"
      Demo = "http://smartadp.chinacloudapp.cn/"
      Authors = ["Dongyu Liu", "Di Weng", "Yuhong Li", "Jie Bao", "Yu Zheng", "Huamin Qu", "Yingcai Wu"]

  [Params.News]
    [[Params.News.Items]]
      Date = "Sep 1, 2017 - Pinned"
      Summary = "We are looking for strongly-motivated PostDoc, PhD, Master, and undergraduate students to join us! If you are interested in visualization research, please <a href=\"#\">contact us</a>."
    [[Params.News.Items]]
      Date = "Nov 24, 2017"
      Summary = "Ji Lan, one of our Ph.D. students, has received National Scholarship. Congratulations!"
    [[Params.News.Items]]
      Date = "Nov 24, 2017"
      Summary = "Junpei Zhou, one of our undergraduate students, has been awarded Chu Kochen Scholarship. This is the second Chu Kochen Scholarship awarded to our undergraduate group members in two consecutive years, congratulations!"
    [[Params.News.Items]]
      Date = "Oct 17, 2017"
      Summary = "Our new site has been deployed! Check at <a href=\"http://zjuvis.org/\">http://zjuvis.org/</a>."

  [Params.Members]
    [[Params.Members.Items]]
      Name = "Xiao Xie"
      Photo = "images/people/xiexiao.jpg"
      Position = "Ph.D. Since 2015"
      URL = "http://ssxiexiao.github.io/about/"
    [[Params.Members.Items]]
      Name = "Xiwen Cai"
      Photo = "images/people/caixiwen.jpg"
      Position = "Master Since 2015"
      URL = "https://github.com/seevencai"
    [[Params.Members.Items]]
      Name = "Di Weng"
      Photo = "images/people/wengdi.jpg"
      Position = "Ph.D. Since 2016"
      URL = "https://polymorphism.ac.cn"
    [[Params.Members.Items]]
      Name = "Ji Lan"
      Photo = "images/people/lanji.png"
      Position = "Ph.D. Since 2016"
      URL = "https://lanjizju.github.io/"
    [[Params.Members.Items]]
      Name = "Tan Tang"
      Photo = "images/people/tangtan.jpg"
      Position = "Ph.D. Since 2016"
      URL = "http://www.tantang.org/"
    [[Params.Members.Items]]
      Name = "Sadia Rubab"
      Photo = "images/people/sadiarubab.png"
      Position = "Ph.D. Since 2017"
      URL = "https://www.researchgate.net/profile/Sadia_Rubab"
    [[Params.Members.Items]]
      Name = "Heming Zhu"
      Photo = "images/people/zhuheming.jpg"
      Position = "Master Since 2017"
      URL = "http://wootwootwo.me/"
    [[Params.Members.Items]]
      Name = "Kaijuan Yuan"
      Photo = "images/people/yuankaijuan.jpg"
      Position = "Master Since 2017"
      URL = "https://www.linkedin.com/in/kaijuan-yuan-362326b9/"
    [[Params.Members.Items]]
      Name = "Kejian Zhao"
      Photo = "images/people/zhaokejian.jpg"
      Position = "Master Since 2017"
      URL = "https://zhaokejian.github.io/about/"
    [[Params.Members.Items]]
      Name = "Dazhen Deng"
      Photo = "images/people/dengdazhen.jpg"
      Position = "Undergraduate"
      URL = "#"
    [[Params.Members.Items]]
      Name = "Hongye Liang"
      Photo = "images/people/lianghongye.jpg"
      Position = "Undergraduate"
      URL = "#"
    [[Params.Members.Items]]
      Name = "Jiachen Wang"
      Photo = "images/people/wangjiachen.jpg"
      Position = "Undergraduate"
      URL = "#"
    [[Params.Members.Items]]
      Name = "Ran Chen"
      Photo = "images/people/chenran.png"
      Position = "Undergraduate"
      URL = "#"
    [[Params.Members.Items]]
      Name = "Yifang Wang"
      Photo = "images/people/wangyifang.jpg"
      Position = "Undergraduate"
      URL = "http://wangyifang.top/about/"
    [[Params.Members.Items]]
      Name = "Zikun Deng"
      Photo = "images/people/dengzikun.jpg"
      Position = "Undergraduate"
      URL = "https://mrsoldiers.github.io/"
